create database tareas;
use tareas;

CREATE TABLE tarea(
	ID INTEGER PRIMARY KEY auto_increment,
    DESCRIPTION VARCHAR(100),
    STATE VARCHAR(40)
);

INSERT INTO tarea(ID,DESCRIPTION,STATE)VALUE(1,'NADAR','PENDIENTE'),
(2,'HACER EJRCICIO','PENDIENTE'),
(3,'IR AL OCULISTA','PENDIENTE');

SELECT * FROM tarea;